from numpy import *
a=array([1,2,3,4])
b=array(a)
c=a
print(a,b,c)
print()
print()
a=linspace(0,1,5)
print(a)
print()
print()
b=logspace(1,4,5)
print(b)
for i in range(len(b)):
    print('%.2f'%b[i],end='___')
print()
print()
print(arange(10))
for i in range(20):
    print(i)
print()
print()
print(zeros(10,int))
print(ones(10,int))
c+=5
print(c)
print()
print()
a=array([1,2,3,6,5,8,7,34,5])
b=array([1,2,4,5,6,76,5,34,6])
print(a==b)
print(a>b)
print(a<b)
print(a!=b)
print(a&b)
print(1 in a)
print(1 not in a)
a[1]=700
print('check')
print(b)
print(a)
print(a>b)
print(any(a>b))
print(all(a>b))
if any(a>b):print(a*b)
print()
print()
print('logical functions')
a=arange(1,10,2)
b=arange(0,10,0.5)
print(logical_and(a>0,a<5))
print()
print(logical_or(b>=0,b==1))
print()
print(logical_not(b))
a=array(arange(10.5,20,5),int)
print('where function')
c=where(a%2==0,a,'c')
print(c)
print(nonzero(c))
print(nonzero(a))
print(nonzero(b))
print('view and copying array')
print(a)
print(b)
d=a.view()
print(d)
d[1]=555
print(a)
print(d)
d=a.copy()
print(d)
d[0]=6666
print(d)
print(a)
