str=input('enter a hexadecimal no.:')
n=int(str,16)
print('hexa to decimal:=', n )
print()
str=input('enter a octal no.:')
m=int(str,8)
print("octa to decimal:= %f"%m, end='___')
print()
str=input('enter a binary no.:')
o=int(str,2)
print('bin to decimal:=',o)
